dist: xenial
language: haxe

haxe:
  - development
  - stable

install:
  - haxelib --global install hmm
  - haxelib --global run hmm setup
  - hmm install

script:
  - haxe dev.hxml
  - haxe -D unlock-actual-cards -D systemd build.hxml
