#!/bin/bash -e

# Standalone(ish) development server
#
# For Linux based systems.  Use from the project root.
# Requires a tora binary in the path.
#
# Start with:
#    docs/dev-server
#
# To get a tora binary in the path:
#    haxe tora.hxml && cp tora.n /tmp && nekotools boot /tmp/tora.n && sudo cp /tmp/tora /usr/local/bin/
#
# Temporary files are stored on `runtime`.

echo "Preparing the development server (tora)"
echo "    http://localhost:8080"
echo
echo -n "Enter the password to AcessoCard's API (and press <Enter>): "
read -s ACESSO_PASSWORD
echo
export ACESSO_PASSWORD

set -x
cd $PWD
mkdir -p runtime
export MAIN_DB=sqlite3://runtime/main.db3
export ACESSO_USERNAME=random.address@company.com
export ACESSO_PRODUCT=ABCDEF123456Z
export SENDGRID_KEY=SG.xxxxxxxxxxxxxx_xxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
export SENDGRID_KEY=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
if [ -f runtime/nginx.pid ]; then
	nginx -c docs/nginx.conf -p '' -s reload
else
	nginx -c docs/nginx.conf -p ''
fi
xdg-open http://localhost:8080 2>/dev/null >/dev/null
tora -fcgi -p 6666

