#!/bin/bash -e

# Standalone(ish) development server
#
# For Linux based systems.  Use from the project root.
# Requires a tora binary in the path.
#
# Start with:
#    docs/dev-server
#
# To get a tora binary in the path:
#    haxe tora.hxml && cp tora.n /tmp && nekotools boot /tmp/tora.n && _ cp /tmp/tora /usr/local/bin/
#
# Temporary files are stored on `runtime`.

echo "Preparing the development server (tora)"

echo -n "Enter the password to AcessoCard's API (and press <Enter>): "
read -s ACESSO_PASSWORD
echo
export ACESSO_PASSWORD

set -x
cd $PWD
mkdir -p runtime
export MAIN_DB=sqlite3://runtime/main.db3
export ACESSO_USERNAME=user.belcorp.acesso@gmail.com
export ACESSO_PRODUCT=CBLBELSQID12V
nginx -c docs/nginx.conf -p '' -s stop ; nginx -c docs/nginx.conf -p ''
tora -fcgi -p 6666

